### PR TITLE
New team: "〈( ^.^)ノ"

### PR DESCRIPTION
**Pull request by grossamos**
Added directory for team `template`

### CODE REVIEW

**Comment by jntrnr** [comment]
Nice try, but that's way too confusing :D

**Comment by grossamos** [comment]
``〈( ^.^)ノ`` look better? :smile:

**Comment by jntrnr** [comment]
Oh my. We'll see how well filesystems handle that one.

Looks like you still have the old name in there, too.

**Comment by grossamos** [comment]
hm, looks like my filesystem/git isn't handling it all to well then xD

**Pull request closed without merging**
