### PR TITLE
Team jam solo: zash Programming Language

### PR DESCRIPTION
**Pull request by jecolon**
Ok, so here we go! The zash Programming Language

### CODE REVIEW

**Comment by jntrnr** [comment]
@jecolon - can you delete the binaries? We only need the source code

**Comment by ZikiFlicky** [comment]
Yo your profile picture is 2112's Starman! cool!

**Comment by jecolon** [comment]
Ok deleted the binaries and updated the README accordingly!

**Comment by jecolon** [comment]
@ZikiFlicky RUSH! Greates band EVER! 🎸

**Comment by jecolon** [comment]
Hi @jntrnr : I'm pretty sure you're super busy but I just wanted to know if my submission will get merged given I made the PR way earlier than the deadline? Thanks!

**Comment by jntrnr** [comment]
Confirmed binaries remove. README updates related to now-removed binaries. Should be good. Thank you!

**Pull request merged**
